const DATA={
 tracker:{brand:'CHEVROLET',model:'TRACKER',year:'2021',km:'100.000 KM',visible:'GRIS PLATA · TECHO SOLAR · LLANTAS DE ALEACIÓN · PANTALLA CENTRAL',photos:[
  ['tracker-01','EXTERIOR','Chevrolet Tracker gris plata, vista delantera derecha',[['ÓPTICA',68,52,'La óptica delantera visible en la foto.','Diseño frontal','La forma y el conjunto de iluminación son parte de lo que se puede verificar a simple vista.'],['LLANTA',82,72,'La llanta delantera derecha.','Detalle de rueda','Un punto de contacto real con el suelo, sin salir de la foto.']]],
  ['tracker-02','TRASERA','Chevrolet Tracker gris plata, vista trasera',[]],
  ['tracker-03','LATERAL','Chevrolet Tracker gris plata, vista lateral',[]],
  ['tracker-04','FRENTE','Chevrolet Tracker gris plata, vista delantera',[]],
  ['tracker-05','INTERIOR','Tablero, volante y pantalla central de Chevrolet Tracker',[['VOLANTE',21,64,'El volante y sus comandos visibles.','Puesto de conducción','La foto permite mirar la disposición del puesto delantero.'],['PANTALLA',50,45,'La pantalla central del tablero.','Centro del tablero','Un detalle de tecnología que sí aparece en esta toma.']]]
 ]},
 palio:{brand:'FIAT',model:'PALIO',year:'2017',km:'128.000 KM',visible:'BLANCO · CINCO PUERTAS · TAPIZADO DE TELA GRIS · CAJA MANUAL',photos:[
  ['palio-01','EXTERIOR','Fiat Palio blanco dentro del salón de Chita',[['ÓPTICA',69,58,'La óptica delantera derecha.','Frente del Palio','La toma permite reconocer el frente y su diseño de iluminación.']]],
  ['palio-02','FRENTE','Fiat Palio blanco, vista delantera',[]],
  ['palio-03','TRASERA','Fiat Palio blanco, vista trasera',[]],
  ['palio-04','INTERIOR','Interior de Fiat Palio',[]]
 ]}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const viewer=$('[data-viewer]'),stage=$('[data-stage]'),image=$('[data-main-image]'),hotspots=$('[data-hotspots]');
const state={unit:'tracker',photo:0,zoom:1,x:0,y:0,drag:false,startX:0,startY:0,originX:0,originY:0,pointers:new Map(),pinchStart:0,pinchZoom:1,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function current(){return DATA[state.unit].photos[state.photo]}
function renderTransform(animated=true){const maxX=viewer.clientWidth*(state.zoom-1)*.55,maxY=viewer.clientHeight*(state.zoom-1)*.55;state.x=clamp(state.x,-maxX,maxX);state.y=clamp(state.y,-maxY,maxY);const value=`translate3d(${state.x}px,${state.y}px,0) scale(${state.zoom})`;if(window.gsap&&!state.reduced&&animated)gsap.to(stage,{duration:.55,x:state.x,y:state.y,scale:state.zoom,ease:'power3.out',overwrite:true});else stage.style.transform=value;$('[data-zoom-label]').textContent=`${Math.round(state.zoom*100)}%`;}
function setZoom(next,focusX=viewer.clientWidth/2,focusY=viewer.clientHeight/2){const old=state.zoom;state.zoom=clamp(next,1,3.2);if(state.zoom!==old){const ratio=state.zoom/old;state.x=focusX-(focusX-state.x)*ratio;state.y=focusY-(focusY-state.y)*ratio;}renderTransform(true);}
function resetView(){state.zoom=1;state.x=0;state.y=0;renderTransform(true);}
function setDetail(h){const panel=$('.detail-panel');if(!h){panel.classList.remove('has-detail');$('[data-detail-title]').innerHTML='Vista<br><em>general</em>';$('[data-detail-copy]').textContent='Una vista real de la unidad publicada. Tocá un punto para mirar más de cerca.';$('[data-detail-question]').textContent='Elegí un detalle sobre la imagen.';$$('.hotspot').forEach(x=>x.classList.remove('is-active'));return}panel.classList.add('has-detail');$('[data-detail-title]').innerHTML=`${h[0].toLowerCase()}<br><em>${h[4]}</em>`;$('[data-detail-copy]').textContent=h[3];$('[data-detail-question]').textContent=h[5];$$('.hotspot').forEach(x=>x.classList.toggle('is-active',x.dataset.name===h[0]));const rect=viewer.getBoundingClientRect();const hx=rect.width*h[1]/100,hy=rect.height*h[2]/100;setZoom(Math.max(state.zoom,1.75),hx,hy);}
function renderHotspots(){hotspots.innerHTML='';const hs=current()[3];hs.forEach(h=>{const b=document.createElement('button');b.type='button';b.className='hotspot';b.style.left=`${h[1]}%`;b.style.top=`${h[2]}%`;b.dataset.name=h[0];b.setAttribute('aria-label',`Ver detalle: ${h[0].toLowerCase()}`);b.innerHTML=`<span>${h[0]}</span>`;b.addEventListener('click',e=>{e.stopPropagation();setDetail(h)});hotspots.append(b)});}
function renderStrip(){const strip=$('[data-photo-strip]');strip.innerHTML='';DATA[state.unit].photos.forEach((p,i)=>{const b=document.createElement('button');b.type='button';b.className=`photo-thumb ${i===state.photo?'is-active':''}`;b.setAttribute('aria-label',`Ver foto ${i+1}: ${p[1].toLowerCase()}`);b.innerHTML=`<img src="images/showroom/${p[0]}.webp" alt="${p[2]}" loading="lazy">`;b.addEventListener('click',()=>setPhoto(i));strip.append(b)});}
function setPhoto(i){state.photo=i;const p=current();setDetail();if(window.gsap&&!state.reduced)gsap.to(image,{opacity:0,duration:.18,onComplete:()=>{image.src=`images/showroom/${p[0]}.webp`;image.alt=p[2];renderHotspots();renderStrip();resetView();gsap.to(image,{opacity:1,duration:.35})}});else{image.src=`images/showroom/${p[0]}.webp`;image.alt=p[2];renderHotspots();renderStrip();resetView();}}
function setUnit(id){state.unit=id;state.photo=0;const u=DATA[id];$$('[data-unit]').forEach(b=>{const active=b.dataset.unit===id;b.classList.toggle('is-active',active);b.setAttribute('aria-selected',String(active));});$('[data-detail-kicker]').textContent=`${u.brand} ${u.model} · ${u.year}`;const text=encodeURIComponent(`Hola, quiero consultar por el ${u.brand} ${u.model} ${u.year}.`);$('[data-whatsapp]').href=`https://wa.me/5493442647442?text=${text}`;setPhoto(0);}
viewer.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===1){state.drag=true;state.startX=e.clientX;state.startY=e.clientY;state.originX=state.x;state.originY=state.y;viewer.classList.add('is-dragging');}else if(state.pointers.size===2){const [a,b]=[...state.pointers.values()];state.pinchStart=Math.hypot(a.x-b.x,a.y-b.y);state.pinchZoom=state.zoom;state.drag=false;}viewer.setPointerCapture?.(e.pointerId);});
viewer.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){const [a,b]=[...state.pointers.values()];const distance=Math.hypot(a.x-b.x,a.y-b.y);const rect=viewer.getBoundingClientRect();setZoom(state.pinchZoom*distance/state.pinchStart,(a.x+b.x)/2-rect.left,(a.y+b.y)/2-rect.top);return}if(!state.drag)return;state.x=state.originX+e.clientX-state.startX;state.y=state.originY+e.clientY-state.startY;renderTransform(false);});
['pointerup','pointercancel'].forEach(type=>viewer.addEventListener(type,e=>{state.pointers.delete(e.pointerId);if(state.pointers.size<2){state.pinchStart=0;state.drag=false;viewer.classList.remove('is-dragging');renderTransform(true);}}));viewer.addEventListener('wheel',e=>{e.preventDefault();const r=viewer.getBoundingClientRect();setZoom(state.zoom+(e.deltaY<0?.18:-.18),e.clientX-r.left,e.clientY-r.top)},{passive:false});viewer.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();setZoom(state.zoom+.35)}if(e.key==='-'||e.key==='_'){e.preventDefault();setZoom(state.zoom-.35)}if(e.key==='0'){e.preventDefault();resetView()}});
$('[data-zoom-in]').addEventListener('click',()=>setZoom(state.zoom+.35));$('[data-zoom-out]').addEventListener('click',()=>setZoom(state.zoom-.35));$('[data-reset]').addEventListener('click',resetView);$('[data-clear]').addEventListener('click',()=>{resetView();setDetail()});$$('[data-unit]').forEach(b=>b.addEventListener('click',()=>setUnit(b.dataset.unit)));
window.addEventListener('resize',()=>renderTransform(false));
renderHotspots();renderStrip();setUnit('tracker');
