const DATA={
 tracker:{brand:'CHEVROLET',model:'TRACKER',year:'2021',km:'100.000 KM',visible:'GRIS PLATA · TECHO SOLAR · LLANTAS DE ALEACIÓN · PANTALLA CENTRAL',photos:[
  ['tracker-01','EXTERIOR','Chevrolet Tracker gris plata, vista delantera derecha',[['ÓPTICA',68,52,'La óptica delantera visible en la foto.','Diseño frontal','La forma y el conjunto de iluminación son parte de lo que se puede verificar a simple vista.'],['LLANTA',82,72,'La llanta delantera derecha.','Detalle de rueda','Un punto de contacto real con el suelo, sin salir de la foto.']]],
  ['tracker-02','TRASERA','Chevrolet Tracker gris plata, vista trasera',[]],
  ['tracker-03','LATERAL','Chevrolet Tracker gris plata, vista lateral',[]],
  ['tracker-04','FRENTE','Chevrolet Tracker gris plata, vista delantera',[]],
  ['tracker-05','INTERIOR','Tablero, volante y pantalla central de Chevrolet Tracker',[['VOLANTE',21,64,'El volante y sus comandos visibles.','Puesto de conducción','La foto permite mirar la disposición del puesto delantero.'],['PANTALLA',50,45,'La pantalla central del tablero.','Centro del tablero','Un detalle de tecnología que sí aparece en esta toma.']]]
 ]},
 palio:{brand:'FIAT',model:'PALIO',year:'2017',km:'128.000 KM',visible:'BLANCO · CINCO PUERTAS · TAPIZADO DE TELA GRIS · CAJA MANUAL',photos:[
  ['palio-01','EXTERIOR','Fiat Palio blanco dentro del salón de Chita',[['ÓPTICA',69,58,'La óptica delantera derecha.','Frente del Palio','La toma permite reconocer el frente y su diseño de iluminación.']]],
  ['palio-02','FRENTE','Fiat Palio blanco, vista delantera',[]],
  ['palio-03','TRASERA','Fiat Palio blanco, vista trasera',[]],
  ['palio-04','INTERIOR','Interior de Fiat Palio',[]]
 ]}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const viewer=$('[data-viewer]'),stage=$('[data-stage]'),image=$('[data-main-image]'),hotspots=$('[data-hotspots]');
const state={unit:'tracker',photo:0,zoom:1,x:0,y:0,drag:false,startX:0,startY:0,originX:0,originY:0,pointers:new Map(),pinchStart:0,pinchZoom:1,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
function current(){return DATA[state.unit].photos[state.photo]}
function renderTransform(animated=true){const maxX=viewer.clientWidth*(state.zoom-1)*.55,maxY=viewer.clientHeight*(state.zoom-1)*.55;state.x=clamp(state.x,-maxX,maxX);state.y=clamp(state.y,-maxY,maxY);const value=`translate3d(${state.x}px,${state.y}px,0) scale(${state.zoom})`;if(window.gsap&&!state.reduced&&animated)gsap.to(stage,{duration:.55,x:state.x,y:state.y,scale:state.zoom,ease:'power3.out',overwrite:true});else stage.style.transform=value;$('[data-zoom-label]').textContent=`${Math.round(state.zoom*100)}%`;}
function setZoom(next,focusX=viewer.clientWidth/2,focusY=viewer.clientHeight/2){const old=state.zoom;state.zoom=clamp(next,1,3.2);if(state.zoom!==old){const ratio=state.zoom/old;state.x=focusX-(focusX-state.x)*ratio;state.y=focusY-(focusY-state.y)*ratio;}renderTransform(true);}
function resetView(){state.zoom=1;state.x=0;state.y=0;renderTransform(true);}
function setDetail(h){const panel=$('.detail-panel');if(!h){panel.classList.remove('has-detail');$('[data-detail-title]').innerHTML='Vista<br><em>general</em>';$('[data-detail-copy]').textContent='Una vista real de la unidad publicada. Tocá un punto para mirar más de cerca.';$('[data-detail-question]').textContent='Elegí un detalle sobre la imagen.';$$('.hotspot').forEach(x=>x.classList.remove('is-active'));return}panel.classList.add('has-detail');$('[data-detail-title]').innerHTML=`${h[0].toLowerCase()}<br><em>${h[4]}</em>`;$('[data-detail-copy]').textContent=h[3];$('[data-detail-question]').textContent=h[5];$$('.hotspot').forEach(x=>x.classList.toggle('is-active',x.dataset.name===h[0]));const rect=viewer.getBoundingClientRect();const hx=rect.width*h[1]/100,hy=rect.height*h[2]/100;setZoom(Math.max(state.zoom,1.75),hx,hy);}
function renderHotspots(){hotspots.innerHTML='';const hs=current()[3];hs.forEach(h=>{const b=document.createElement('button');b.type='button';b.className='hotspot';b.style.left=`${h[1]}%`;b.style.top=`${h[2]}%`;b.dataset.name=h[0];b.setAttribute('aria-label',`Ver detalle: ${h[0].toLowerCase()}`);b.innerHTML=`<span>${h[0]}</span>`;b.addEventListener('click',e=>{e.stopPropagation();setDetail(h)});hotspots.append(b)});}
function renderStrip(){const strip=$('[data-photo-strip]');strip.innerHTML='';DATA[state.unit].photos.forEach((p,i)=>{const b=document.createElement('button');b.type='button';b.className=`photo-thumb ${i===state.photo?'is-active':''}`;b.setAttribute('aria-label',`Ver foto ${i+1}: ${p[1].toLowerCase()}`);b.innerHTML=`<img src="images/showroom/${p[0]}.webp" alt="${p[2]}" loading="lazy">`;b.addEventListener('click',()=>setPhoto(i));strip.append(b)});}
function setPhoto(i){state.photo=i;const p=current();setDetail();if(window.gsap&&!state.reduced)gsap.to(image,{opacity:0,duration:.18,onComplete:()=>{image.src=`images/showroom/${p[0]}.webp`;image.alt=p[2];renderHotspots();renderStrip();resetView();gsap.to(image,{opacity:1,duration:.35})}});else{image.src=`images/showroom/${p[0]}.webp`;image.alt=p[2];renderHotspots();renderStrip();resetView();}}
function setUnit(id){state.unit=id;state.photo=0;const u=DATA[id];$$('[data-unit]').forEach(b=>{const active=b.dataset.unit===id;b.classList.toggle('is-active',active);b.setAttribute('aria-selected',String(active));});$('[data-detail-kicker]').textContent=`${u.brand} ${u.model} · ${u.year}`;const text=encodeURIComponent(`Hola, quiero consultar por el ${u.brand} ${u.model} ${u.year}.`);$('[data-whatsapp]').href=`https://wa.me/5493442647442?text=${text}`;setPhoto(0);}
viewer.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===1){state.drag=true;state.startX=e.clientX;state.startY=e.clientY;state.originX=state.x;state.originY=state.y;viewer.classList.add('is-dragging');}else if(state.pointers.size===2){const [a,b]=[...state.pointers.values()];state.pinchStart=Math.hypot(a.x-b.x,a.y-b.y);state.pinchZoom=state.zoom;state.drag=false;}viewer.setPointerCapture?.(e.pointerId);});
viewer.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size===2){const [a,b]=[...state.pointers.values()];const distance=Math.hypot(a.x-b.x,a.y-b.y);const rect=viewer.getBoundingClientRect();setZoom(state.pinchZoom*distance/state.pinchStart,(a.x+b.x)/2-rect.left,(a.y+b.y)/2-rect.top);return}if(!state.drag)return;state.x=state.originX+e.clientX-state.startX;state.y=state.originY+e.clientY-state.startY;renderTransform(false);});
['pointerup','pointercancel'].forEach(type=>viewer.addEventListener(type,e=>{state.pointers.delete(e.pointerId);if(state.pointers.size<2){state.pinchStart=0;state.drag=false;viewer.classList.remove('is-dragging');renderTransform(true);}}));viewer.addEventListener('wheel',e=>{e.preventDefault();const r=viewer.getBoundingClientRect();setZoom(state.zoom+(e.deltaY<0?.18:-.18),e.clientX-r.left,e.clientY-r.top)},{passive:false});viewer.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();setZoom(state.zoom+.35)}if(e.key==='-'||e.key==='_'){e.preventDefault();setZoom(state.zoom-.35)}if(e.key==='0'){e.preventDefault();resetView()}});
$('[data-zoom-in]').addEventListener('click',()=>setZoom(state.zoom+.35));$('[data-zoom-out]').addEventListener('click',()=>setZoom(state.zoom-.35));$('[data-reset]').addEventListener('click',resetView);$('[data-clear]').addEventListener('click',()=>{resetView();setDetail()});$$('[data-unit]').forEach(b=>b.addEventListener('click',()=>setUnit(b.dataset.unit)));
window.addEventListener('resize',()=>renderTransform(false));
renderHotspots();renderStrip();setUnit('tracker');

/* LONGFORM SYSTEM — un solo lenguaje de movimiento para todo el recorrido */
const routeStates=[
 {copy:'Para moverte todos los días.',unit:'FIAT PALIO / 2017 · 128.000 KM',x:'0vw',y:'0vh',scale:1},
 {copy:'Para abrir distancia.',unit:'CHEVROLET TRACKER / 2021 · 100.000 KM',x:'-3vw',y:'-1vh',scale:1.06},
 {copy:'Para todo lo que viene.',unit:'CHEVROLET TRACKER / 2021 · 100.000 KM',x:'2vw',y:'-2vh',scale:1.12},
 {copy:'Para que el día rinda.',unit:'FIAT PALIO / 2017 · 128.000 KM',x:'4vw',y:'0vh',scale:1.03},
 {copy:'Para salir de la línea.',unit:'CHEVROLET TRACKER / 2021 · 100.000 KM',x:'-1vw',y:'-4vh',scale:1.16}
];
const routeStory=$('.route-story');
if(routeStory){const routeImg=routeStory.querySelector('.route-art img'),routeCopy=routeStory.querySelector('[data-route-copy]'),routeUnit=routeStory.querySelector('[data-route-unit]');$$('[data-route-tab]').forEach((b,i)=>b.addEventListener('click',()=>{const s=routeStates[i];$$('[data-route-tab]').forEach((x,n)=>x.classList.toggle('is-active',n===i));routeCopy.textContent=s.copy;routeUnit.textContent=s.unit;if(window.gsap&&!state.reduced)gsap.to(routeImg,{duration:.7,x:s.x,y:s.y,scale:s.scale,ease:'power3.out'});else routeImg.style.transform=`translate3d(${s.x},${s.y},0) scale(${s.scale})`;}));}
const briefingStory=$('.briefing-story');
if(briefingStory){const scenes=[['EXTERIOR','Una mirada real, sin intermediarios. La unidad como aparece en la calle.','images/showroom/tracker-01.webp'],['INTERIOR','Entrá al habitáculo: volante, tablero y pantalla que sí están en la foto.','images/showroom/tracker-05.webp'],['DATOS','Lo que necesitás recordar: modelo, año y kilómetros publicados.','images/showroom/tracker-03.webp'],['CONTACTO','Si te hizo frenar, el próximo paso es hablar con Chita.','images/showroom/palio-01.webp']];const img=briefingStory.querySelector('[data-briefing-image]'),tag=briefingStory.querySelector('[data-briefing-tag]'),copy=briefingStory.querySelector('[data-briefing-copy]'),progress=briefingStory.querySelector('[data-briefing-progress]');$$('[data-briefing-stage]').forEach((b,i)=>b.addEventListener('click',()=>{const s=scenes[i];$$('[data-briefing-stage]').forEach((x,n)=>x.classList.toggle('is-active',n===i));tag.textContent=s[0];copy.textContent=s[1];progress.style.width=`${(i+1)*25}%`;if(window.gsap&&!state.reduced)gsap.fromTo(img,{opacity:.35,x:'4vw',scale:1.08},{opacity:1,x:0,scale:1,duration:.65,ease:'power3.out'});img.src=s[2];}));}
const videoToggle=$('[data-video-toggle]'),ambientVideo=$('.passed-media video');if(videoToggle&&ambientVideo)videoToggle.addEventListener('click',()=>{if(ambientVideo.paused){ambientVideo.play();videoToggle.innerHTML='PAUSAR ESCENA <span>Ⅱ</span>';}else{ambientVideo.pause();videoToggle.innerHTML='REPRODUCIR ESCENA <span>▶</span>';}});
if(window.gsap&&window.ScrollTrigger&&!state.reduced){gsap.registerPlugin(ScrollTrigger);const ctx=gsap.context(()=>{gsap.utils.toArray('.long-intro,.route-story,.briefing-story,.passed-by,.sound-story,.behind-story,.open-auto,.journey-story,.calendar-story').forEach(section=>{const visual=section.querySelector('img,video,.sound-wheel,.calendar-mark');if(visual)gsap.fromTo(visual,{y:34,opacity:.55},{y:0,opacity:1,ease:'none',scrollTrigger:{trigger:section,start:'top 82%',end:'top 30%',scrub:.7}});});gsap.fromTo('.hotspot',{scale:.65,opacity:0},{scale:1,opacity:1,stagger:.12,duration:.7,ease:'power3.out',scrollTrigger:{trigger:'.viewer',start:'top 78%'}});});window.addEventListener('pagehide',()=>ctx.revert(),{once:true});}

/* DISTANCE MAP — coordenadas reales, trazado explícitamente orientativo */
const distanceSection=$('.distance-experience');
if(distanceSection){
 const locations={
  gualeguaychu:{name:'GUALEGUAYCHÚ',lat:-33.0078908,lon:-58.5109859,km:73,time:'≈ 1 h 04 min',minutes:64},
  colon:{name:'COLÓN',lat:-32.2182804,lon:-58.1356171,km:47,time:'≈ 37 min',minutes:37},
  villaguay:{name:'VILLAGUAY',lat:-31.8676271,lon:-59.0270174,km:129,time:'≈ 1 h 35 min',minutes:95},
  parana:{name:'PARANÁ',lat:-31.7330145,lon:-60.5298511,km:265,time:'≈ 3 h 16 min',minutes:196},
  concordia:{name:'CONCORDIA',lat:-31.3401914,lon:-58.0263642,km:154,time:'≈ 1 h 50 min',minutes:110},
  federacion:{name:'FEDERACIÓN',lat:-30.9856574,lon:-57.9194395,km:197,time:'≈ 2 h 17 min',minutes:137},
  concepcion:{name:'CONCEPCIÓN DEL URUGUAY',lat:-32.4851849,lon:-58.2320232,km:0,time:'≈ 0 min',minutes:0}
 };
 const map=distanceSection.querySelector('.distance-map'),nodes=distanceSection.querySelector('[data-map-nodes]'),labels=distanceSection.querySelector('[data-map-labels]'),path=distanceSection.querySelector('[data-route-path]'),glow=distanceSection.querySelector('[data-route-glow]'),select=distanceSection.querySelector('[data-distance-select]'),chita=distanceSection.querySelector('.chita-node'),ring=distanceSection.querySelector('.chita-ring');
 const minLon=-60.8,maxLon=-57.7,minLat=-33.3,maxLat=-30.7, mapPoint=l=>({x:100+(l.lon-minLon)/(maxLon-minLon)*600,y:70+(maxLat-l.lat)/(maxLat-minLat)*410});
 const dest=mapPoint(locations.concepcion);chita.setAttribute('cx',dest.x);chita.setAttribute('cy',dest.y);ring.setAttribute('cx',dest.x);ring.setAttribute('cy',dest.y);
 Object.entries(locations).forEach(([id,loc])=>{if(id==='concepcion')return;const p=mapPoint(loc);const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r','5');c.classList.add('map-node');c.dataset.location=id;c.setAttribute('tabindex','0');c.setAttribute('role','button');c.setAttribute('aria-label',`Seleccionar ${loc.name}`);c.addEventListener('click',()=>selectLocation(id));c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectLocation(id)}});nodes.append(c);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',p.x+10);t.setAttribute('y',p.y-10);t.textContent=loc.name;t.classList.add('map-node-label');t.dataset.locationLabel=id;labels.append(t);});
 function selectLocation(id){const loc=locations[id];select.value=id;distanceSection.dataset.mapSelected='true';distanceSection.querySelector('[data-distance-from]').textContent=loc.name;distanceSection.querySelector('[data-distance-km]').textContent=`${loc.km} km`;distanceSection.querySelector('[data-distance-time]').textContent=loc.time;distanceSection.querySelector('[data-distance-maps]').href=`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(loc.name+', Entre Ríos, Argentina')}&destination=Chita+Automotores%2C+Gral.+Galarza+1712%2C+Concepci%C3%B3n+del+Uruguay`;
  const start=mapPoint(loc),midX=(start.x+dest.x)/2,midY=Math.min(start.y,dest.y)-90;const d=`M ${start.x} ${start.y} Q ${midX} ${midY} ${dest.x} ${dest.y}`;path.setAttribute('d',d);glow.setAttribute('d',d);const length=path.getTotalLength();path.style.strokeDasharray=length;glow.style.strokeDasharray=length;path.style.strokeDashoffset=length;glow.style.strokeDashoffset=length;nodes.querySelectorAll('.map-node').forEach(n=>n.classList.toggle('is-active',n.dataset.location===id));labels.querySelectorAll('.map-node-label').forEach(n=>n.classList.toggle('is-active',n.dataset.locationLabel===id));
  if(window.gsap&&!state.reduced){const tl=gsap.timeline();tl.to([path,glow],{strokeDashoffset:0,duration:1.1,ease:'power2.inOut'}).fromTo('[data-distance-km]',{opacity:0,y:10},{opacity:1,y:0,duration:.35},'-=.25').fromTo('[data-distance-time]',{opacity:0,y:10},{opacity:1,y:0,duration:.35},'-=.15');}else{path.style.strokeDashoffset=0;glow.style.strokeDashoffset=0;}
 }
 select.addEventListener('change',()=>selectLocation(select.value));selectLocation('gualeguaychu');
 if(window.gsap&&window.ScrollTrigger&&!state.reduced){gsap.fromTo(distanceSection.querySelector('.distance-map'),{opacity:.15,scale:.92},{opacity:1,scale:1,duration:1,ease:'power3.out',scrollTrigger:{trigger:distanceSection,start:'top 80%',once:true}});}
}
