const zones=[
 ['CARROCERÍA','assets/12.jpg','La unidad completa, tal como aparece en la foto exterior.','foto 12 · vista delantera derecha.'],
 ['RUEDAS','assets/13.jpg','Llantas de aleación con diseño de rayos · visible en foto.','foto 13 · lateral derecho.'],
 ['ÓPTICAS','assets/14.jpg','Ópticas delanteras y traseras · visible en foto.','fotos 14–15 · exterior.'],
 ['INTERIOR','assets/3.jpg','Butacas delanteras en dos tonos · visible en foto.','foto 3 · interior delantero.'],
 ['TABLERO','assets/26.jpg','Volante y pantalla central · visible en foto.','foto 26 · tablero y consola.'],
 ['MOTOR','', 'Sin foto real de motor recibida. La cilindrada se declara solo con el dato del flyer: 1.2T.','sin foto de motor · dato del flyer.']
];
const zoneRoot=document.querySelector('[data-abrir]');
if(zoneRoot){const image=zoneRoot.querySelector('[data-abrir-image]'),title=zoneRoot.querySelector('[data-abrir-title]'),copy=zoneRoot.querySelector('[data-abrir-copy]'),source=zoneRoot.querySelector('[data-abrir-source]'),num=zoneRoot.querySelector('[data-abrir-num]'),motor=zoneRoot.querySelector('[data-abrir-motor]');let active=0;const setZone=i=>{active=Math.max(0,Math.min(5,i));const z=zones[active];title.textContent=z[0];copy.textContent=z[2];source.textContent=z[3];num.textContent=String(active+1).padStart(2,'0');motor.hidden=active!==5;image.hidden=active===5;if(z[1]){image.src=z[1];image.alt=z[0]+' del Chevrolet Tracker, visible en foto.'}zoneRoot.querySelectorAll('[data-abrir-zone]').forEach((b,k)=>b.classList.toggle('is-active',k===active))};zoneRoot.querySelectorAll('[data-abrir-zone]').forEach((b,i)=>b.addEventListener('click',()=>setZone(i)));zoneRoot.querySelector('[data-abrir-prev]').addEventListener('click',()=>setZone(active-1));zoneRoot.querySelector('[data-abrir-next]').addEventListener('click',()=>setZone(active+1));setZone(0)}
const lens=document.querySelector('[data-mini-lens]');
if(lens){const stage=lens.closest('[data-detras]'),img=stage.querySelector('[data-mini-image]'),buttons=[...stage.querySelectorAll('[data-mini-layer]')],layers=[['EXTERIOR','assets/12.jpg','Frente y lateral del vehículo · foto 12.'],['INTERIOR','assets/3.jpg','Butacas delanteras en dos tonos · visible en foto.'],['DETALLES','assets/26.jpg','Volante y pantalla central · visible en foto.']];let layer=0,x=innerWidth*.7,y=innerHeight*.45;const move=(px,py)=>{x=px;y=py;lens.style.transform=`translate3d(${Math.round(x-lens.offsetWidth/2)}px,${Math.round(y-lens.offsetHeight/2)}px,0)`};stage.addEventListener('pointermove',e=>move(e.clientX,e.clientY));stage.addEventListener('pointerdown',e=>{stage.setPointerCapture(e.pointerId);move(e.clientX,e.clientY)});const setLayer=i=>{layer=(i+3)%3;img.src=layers[layer][1];stage.querySelector('[data-mini-name]').textContent=layers[layer][0];stage.querySelector('[data-mini-copy]').textContent=layers[layer][2];buttons.forEach((b,k)=>b.classList.toggle('is-active',k===layer))};buttons.forEach((b,i)=>b.addEventListener('click',()=>setLayer(i)));stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight')setLayer(layer+1);if(e.key==='ArrowLeft')setLayer(layer-1)});setLayer(0)}
